name: build

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  build-android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: zulu
      - uses: subosito/flutter-action@v2
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter build apk --target-platform android-arm64
      - uses: actions/upload-artifact@v2
        with:
          name: android-arm64
          path: build/app/outputs/apk/release/app-release.apk

  build-web:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8'
      - run: flutter pub get
      - run: flutter build web
      - uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build/web

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux
      - uses: actions/upload-artifact@v2
        with:
          name: linux-x64
          path: build/linux/release/bundle
